### ISSUE TITLE
如何获取代码中的openId

### ISSUE THREAD

**Issue by TianLuhua** [killall-love/a-sheep-assistant#1]

**Comment by killall-love** [comment]
打开电脑微信或者手机微信
移出小程序 (羊)
抓包微信
找到  login_wx的接口名称

里面有  openid 还有 token

就看你想用那种方式了

**Comment by killall-love** [comment]
打开电脑微信或者手机微信
移出小程序 (羊)

重新打开(羊)小程序
抓包微信
点击加入羊群
授权后
找到 login_wx的接口名称

里面有 openid 还有 token

就看你想用那种方式了

**Comment by 19819068211** [comment]
请问抖音版有没有办法

**Comment by killall-love** [comment]
抖音 直接用token把  openid是微信的

**Comment by killall-love** [comment]
over
